#!/bin/sh
rm -f "$HOME/.cache/ncmpcpp/icon.jpg"
ffmpeg -hide_banner -loglevel 8 -i "$HOME/music/$(mpc current -f %file%)" -f mjpeg "$HOME/.cache/ncmpcpp/icon.jpg" && notify-send -i "$HOME/.cache/ncmpcpp/icon.jpg" "Now Playing" "$(mpc --format '%title% \n%artist% - %album%' current)" && rm "$HOME/.cache/ncmpcpp/icon.jpg" || notify-send "Now Playing" "$(mpc --format '%title% \n%artist% - %album%' current)"
